# Simple Makefile that always builds everything

CC := gcc
CFLAGS := -g -Wall -std=gnu17

all:
	gcc $(CFLAGS) -o decoder1 8086_decoder1.c
	gcc $(CFLAGS) -o decoder2 8086_decoder2.c
	gcc $(CFLAGS) -o decoder3 8086_decoder3.c
